/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyAccounting;

/**
 *
 * @author MCREMOTE
 */
public class Buh_NormalVMB extends Buh_Basic {

    /**
     * Creates new form BuhBasicCalc
     */
    public Buh_NormalVMB() {
        initComponents();
        setTitle("NormalVMB");
        initOther();
        jButton2.setVisible(false);
    }

    private void initOther() {
        init();
    }

    @Override
    protected void defineMomsTextField() {
        textFieldMoms = jTextField_moms;
    }

    @Override
    protected void defineTextArea() {
        jtextAreaOutPut = jTextArea1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1_inkops_pris = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField_moms = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1_inkops_pris.setText("0");

        jTextField2.setText("0");

        jLabel1.setText("Inköps pris");

        jLabel2.setText("Försäljnings pris");

        jButton1.setText("Calc");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField_moms.setText("0.25");

        jLabel3.setText("Moms");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField4.setText("0.2897");

        jLabel4.setText("Arb avgift / Egen avg.");

        jTextField5.setText("0");

        jLabel5.setText("Frakt");

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jButton2.setText("Go");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1_inkops_pris)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(jTextField2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1))
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_moms, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_moms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1_inkops_pris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(4, 4, 4)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CALC();
        AFTER_CALC();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CALC_B();
        AFTER_CALC();
    }//GEN-LAST:event_jButton2ActionPerformed

    protected double getInkopsPris() {
        return Double.parseDouble(jTextField1_inkops_pris.getText());
    }

    protected double getForsaljningsPris() {
        return Double.parseDouble(jTextField2.getText());
    }

    protected double getFrakt() {
        return Double.parseDouble(jTextField5.getText());
    }

    protected double getVinstMargianl() {
        return getForsaljningsPris() - getInkopsPris();
    }

    protected double getBeskattningsUnderlag() {
        return getVinstMargianl() * 0.8;
    }

    protected double getEgenAvgifterSkatteSats() {
        return Double.parseDouble(jTextField4.getText());
    }

    protected double getVMB() {
        return getBeskattningsUnderlag() * getMomsSats();
    }

    protected boolean isForlust() {
        if (getForsaljningsPris() - getInkopsPris() > 0) {
            return false;
        } else {
            return true;
        }
    }

    protected void CALC_B() {

    }

    @Override
    protected void CALC() {
        //
        jTextArea1.setText("");
        showMessage("---------------------", "----------------------------");
        //
        double vinstMarginal = getVinstMargianl();
        double beskattUnderlag = getBeskattningsUnderlag();
        double totalCirkaSkatt = beskattUnderlag * getEgenAvgifterSkatteSats();
        double cirkaVinst = beskattUnderlag - totalCirkaSkatt;
        showMessage("vinstmarginal / 3028 / D", "" + vinstMarginal);
        showMessage("beskattningsunderlag / 3030 / K", "" + beskattUnderlag);
        showMessage("vmb = beskattningsunderlag * momssats", "");
        showMessage("vmb / 2616 / K", "" + getVMB());
        showMessage("Cirka skatt", "" + totalCirkaSkatt);
        showMessage("Cirka vinst", "" + cirkaVinst);
        showMessage("---------------------", "----------------------------");
        //
        showMessage_debet_kredit_header();
        //
        if (isForlust() == false) {
            if (getFrakt() == 0) {
                showMessage_b(Buh_Konto.KASSA, "debet", getForsaljningsPris());
                showMessage_b(Buh_Konto.FORSALJNING_VMB_VAROR, "kredit", getForsaljningsPris());
                showMessage_b(Buh_Konto.POSITIV_VM_OMFORING, "debet", vinstMarginal);
                showMessage_b(Buh_Konto.POSITIV_VM_BESKATT_UNDERLAG, "kredit", beskattUnderlag);
                showMessage_b(Buh_Konto.UTG_MOMS_VMB_25_PROCENT, "kredit", getVMB());
            } else {
                showMessage_b(Buh_Konto.KASSA, "debet", (getForsaljningsPris() + getFrakt()));
                showMessage_b(Buh_Konto.FRAKTER, "kredit", getFrakt());
                showMessage_b(Buh_Konto.FORSALJNING_VMB_VAROR, "kredit", getForsaljningsPris());
                showMessage_b(Buh_Konto.POSITIV_VM_OMFORING, "debet", vinstMarginal);
                showMessage_b(Buh_Konto.POSITIV_VM_BESKATT_UNDERLAG, "kredit", beskattUnderlag);
                showMessage_b(Buh_Konto.UTG_MOMS_VMB_25_PROCENT, "kredit", getVMB());
            }
        } else { // Förlust
            //
            if (getFrakt() == 0) {
                showMessage_b(Buh_Konto.KASSA, "debet", getForsaljningsPris());
                showMessage_b(Buh_Konto.FORSALJNING_VMB_VAROR, "kredit", getForsaljningsPris());
            } else {
                showMessage_b(Buh_Konto.KASSA, "debet", (getForsaljningsPris() + getFrakt()));
                showMessage_b(Buh_Konto.FRAKTER, "kredit", getFrakt());
                showMessage_b(Buh_Konto.FORSALJNING_VMB_VAROR, "kredit", getForsaljningsPris());
            }
            //
            showMessage("\nOBS! Det här är en Förlust Försäljning", "");
            //
        }
        //
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buh_NormalVMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buh_NormalVMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buh_NormalVMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buh_NormalVMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Buh_NormalVMB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    protected javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    protected javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTextArea jTextArea1;
    protected javax.swing.JTextField jTextField1_inkops_pris;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField_moms;
    // End of variables declaration//GEN-END:variables
}
